# Azure DevOps Pipeline deploying a dev environement
trigger: none
pr: none

variables:
  - template: vars.yml

jobs:
  - job: "Deploy_new_shared_env"
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - template: ./templates/template-setup-golang-env.yml
        parameters:
          gobin: ${{ variables.GOBIN }}
          gopath: ${{ variables.GOPATH }}
          goroot: ${{ variables.GOROOT }}
          modulePath: ${{ variables.modulePath }}
      - template: ./templates/template-setup-azure-tools.yml
        parameters:
          workingDirectory: ${{ variables.modulePath }}
      - template: ./templates/template-az-cli-login.yml
        parameters:
          workingDirectory: ${{ variables.modulePath }}
          azureDevOpsJSONSPN: $(aro-v4-e2e-devops-spn)
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "proxy-e2e"
          outputPath: ${{ variables.modulePath }}/secrets/proxy
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "proxy-e2e-client"
          outputPath: ${{ variables.modulePath }}/secrets/proxy-client
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "vpn-e2e-ca"
          outputPath: ${{ variables.modulePath }}/secrets/vpn-ca
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "firstparty-e2e"
          outputPath: ${{ variables.modulePath }}/secrets/firstparty-development
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "rp-e2e"
          outputPath: ${{ variables.modulePath }}/secrets/localhost
      - template: ./templates/template-pull-certs-from-kv.yml
        parameters:
          kvName: "aro-e2e-global"
          certName: "vpn-e2e-client"
          outputPath: ${{ variables.modulePath }}/secrets/vpn-client
      - template: ./templates/template-prepare-secrets-env.yml
        parameters:
          adminObjectId: $(ARO_V4_E2E_SPN_OBJECT_ID)
          parentDomainName: $(PARENT_DOMAIN_NAME)
          parentDomainRg: $(PARENT_DOMAIN_RG)
          pullSecret: $(aro-v4-e2e-pull-secret)
          azureTenantId: $(AZURE_TENANT_ID)
          azureSubscriptionId: $(AZURE_SUBSCRIPTION_ID)
          azureArmClientSecret: $(aro-v4-e2e-arm-shared-secret)
          azureArmClientId: $(aro-v4-e2e-arm-shared-id)
          azureFpClientId: $(aro-v4-e2e-fp-shared-id)
          azureClientSecret: $(aro-v4-e2e-rp-shared-secret)
          azureClientId: $(aro-v4-e2e-rp-shared-id)
          rgPrefix: $(RG_PREFIX)
          proxyDomainNameLabel: $(PROXY_DOMAIN_NAME_LABEL)
          workingDirectory: ${{ variables.modulePath }}
          proxyIdRsaPub: $(aro-v4-e2e-proxy-ssh-publickey)
          location: $(LOCATION)
      - template: ./templates/template-deploy-shared-env.yml
        parameters:
          azureFpClientSPNId: $(aro-v4-e2e-fp-shared-spn-id)
          azureArmClientSPNId: $(aro-v4-e2e-rp-shared-spn-id)
          workingDirectory: ${{ variables.modulePath }}
